begin;
select plan(18);
select has_table('public','agency_passengers','passengers exist');
select has_table('public','reservations','reservations exist');
select has_table('public','reservation_passengers','reservation snapshots exist');
select has_table('public','seat_holds','capacity holds exist');
select has_table('public','seat_assignments','seat assignments exist');
select has_table('public','approval_requests','approvals exist');
select has_table('public','sales_attributions','sales attribution exists');
select col_type_is('public','reservations','total_amount','numeric(14,2)','reservation money is exact');
select col_type_is('public','reservation_passengers','sale_price','numeric(14,2)','passenger money is exact');
select has_column('public','reservation_passengers','discount_amount','discount snapshot exists');
select ok('HOLD'<>all(enum_range(null::public.reservation_status)::text[]),'HOLD is not reservation status');
select ok('WAITING_PAYMENT'<>all(enum_range(null::public.reservation_status)::text[]),'WAITING_PAYMENT is not reservation status');
select ok('SOLD_OUT'<>all(enum_range(null::public.reservation_status)::text[]),'SOLD_OUT is derived');
select has_function('public','create_manual_reservation',array['uuid','uuid','text','text','timestamp with time zone'],'reservation creation is transactional');
select has_function('public','add_reservation_passenger',array['uuid','uuid','uuid','numeric','uuid'],'passenger and hold are transactional');
select has_function('public','submit_reservation',array['uuid'],'submission is controlled by backend');
select has_function('public','expire_reservations',array[]::text[],'backend expiry exists');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.reservations'::regclass),'reservation RLS is forced');
select * from finish();
rollback;
