export type Json = | string | number | boolean | null | { [key: string]: Json | undefined } | Json[]
export type Database = {
  public: {
    Tables: {
      accounts: { Row: { created_at: string; id: string; legal_name: string }, Insert: { created_at?: string; id?: string; legal_name: string }, Update: { created_at?: string; id?: string; legal_name?: string }, Relationships: [] },
      agencies: { Row: { account_id: string; created_at: string; id: string; name: string }, Insert: { account_id: string; created_at?: string; id?: string; name: string }, Update: { account_id?: string; created_at?: string; id?: string; name?: string }, Relationships: [] },
      agency_members: { Row: { id: string; agency_id: string; user_id: string; role: string; status: string; created_at: string }, Insert: { id?: string; agency_id: string; user_id: string; role: string; status?: string; created_at?: string }, Update: { id?: string; agency_id?: string; user_id?: string; role?: string; status?: string; created_at?: string }, Relationships: [] },
      agency_customers: { Row: { id: string; agency_id: string; auth_user_id: string | null; full_name: string; email: string; phone: string | null; document: string; birth_date: string; status: string; created_at: string; updated_at: string; archived_at: string | null }, Insert: { id?: string; agency_id: string; auth_user_id?: string | null; full_name: string; email: string; phone?: string | null; document: string; birth_date: string; status?: string; created_at?: string; updated_at?: string; archived_at?: string | null }, Update: { id?: string; agency_id?: string; auth_user_id?: string | null; full_name?: string; email?: string; phone?: string | null; document?: string; birth_date: string; status?: string; updated_at?: string; archived_at?: string | null }, Relationships: [] },
      agency_passengers: { Row: { id: string; agency_id: string; owner_customer_id: string | null; linked_auth_user_id: string | null; full_name: string; document: string; birth_date: string; phone: string | null; status: string; created_at: string; updated_at: string }, Insert: { id?: string; agency_id: string; owner_customer_id?: string | null; linked_auth_user_id?: string | null; full_name: string; document: string; birth_date: string; phone?: string | null; status?: string; created_at?: string; updated_at?: string }, Update: { id?: string; agency_id?: string; owner_customer_id?: string | null; linked_auth_user_id?: string | null; full_name?: string; document?: string; birth_date?: string; phone?: string | null; status?: string; updated_at?: string }, Relationships: [] },
      reservations: { Row: { id: string; agency_id: string; trip_id: string; buyer_customer_id: string; code: string; total_amount: number; status: string; financial_status: string; created_at: string; updated_at: string }, Insert: { id?: string; agency_id: string; trip_id: string; buyer_customer_id: string; code: string; total_amount: number; status?: string; financial_status?: string; created_at?: string; updated_at?: string }, Update: { id?: string; agency_id?: string; trip_id?: string; buyer_customer_id?: string; code?: string; total_amount?: number; status?: string; financial_status?: string; updated_at?: string }, Relationships: [] },
      reservation_passengers: { Row: { id: string; agency_id: string; reservation_id: string; trip_id: string; passenger_id: string | null; passenger_name_snapshot: string; document_snapshot: string; birth_date_snapshot: string; category_id: string; category_name_snapshot: string; boarding_point_id: string; boarding_snapshot: string; occupies_seat: boolean; list_price: number; sale_price: number; discount_amount: number; status: string; created_at: string; cancelled_at: string | null }, Insert: { id?: string; agency_id: string; reservation_id: string; trip_id: string; passenger_id?: string | null; passenger_name_snapshot: string; document_snapshot: string; birth_date_snapshot: string; category_id: string; category_name_snapshot: string; boarding_point_id: string; boarding_snapshot: string; occupies_seat?: boolean; list_price: number; sale_price: number; discount_amount?: number; status?: string; created_at?: string; cancelled_at?: string | null }, Update: { id?: string; agency_id?: string; reservation_id?: string; trip_id?: string; passenger_id?: string | null; passenger_name_snapshot?: string; document_snapshot?: string; birth_date_snapshot?: string; category_id?: string; category_name_snapshot: string; boarding_point_id?: string; boarding_snapshot?: string; occupies_seat?: boolean; list_price?: number; sale_price?: number; discount_amount?: number; status?: string; created_at?: string; cancelled_at?: string | null }, Relationships: [] },
      seat_holds: { Row: { id: string; agency_id: string; trip_id: string; seat_id: string; customer_id: string; created_at: string; expires_at: string }, Insert: { id?: string; agency_id: string; trip_id: string; seat_id: string; customer_id: string; created_at?: string; expires_at: string }, Update: { id?: string; agency_id?: string; trip_id?: string; seat_id?: string; customer_id?: string; created_at?: string; expires_at?: string }, Relationships: [] },
      seat_assignments: { Row: { id: string; agency_id: string; trip_id: string; reservation_passenger_id: string; seat_id: string; assigned_at: string; released_at: string | null; release_reason: string | null }, Insert: { id?: string; agency_id: string; trip_id: string; reservation_passenger_id: string; seat_id: string; assigned_at?: string; released_at?: string | null; release_reason?: string | null }, Update: { id?: string; agency_id?: string; trip_id?: string; reservation_passenger_id?: string; seat_id: string; assigned_at?: string; released_at?: string | null; release_reason?: string | null }, Relationships: [] },
      trips: { Row: { agency_id: string; code: string; title: string; destination: string; departure_at: string; return_at: string; status: string; id: string; created_at: string; updated_at: string }, Insert: { id?: string; agency_id: string; code: string; title: string; destination: string; departure_at: string; return_at: string; status?: string; created_at?: string; updated_at?: string }, Update: { id?: string; agency_id?: string; code?: string; title?: string; destination?: string; departure_at?: string; return_at?: string; status?: string; updated_at?: string }, Relationships: [] },
      trip_seats: { Row: { id: string; agency_id: string; trip_id: string; label: string; blocked: boolean; active: boolean }, Insert: { id?: string; agency_id: string; trip_id: string; label: string; blocked?: boolean; active?: boolean }, Update: { id?: string; agency_id?: string; trip_id?: string; label?: string; blocked?: boolean; active?: boolean }, Relationships: [] },
      passenger_categories: { Row: { id: string; agency_id: string; name: string; occupies_seat_default: boolean; active: boolean }, Insert: { id?: string; agency_id: string; name: string; occupies_seat_default?: boolean; active?: boolean }, Update: { id?: string; agency_id?: string; name?: string; occupies_seat_default?: boolean; active?: boolean }, Relationships: [] },
      agency_boarding_locations: { Row: { id: string; agency_id: string; name: string; address: string; active: boolean }, Insert: { id?: string; agency_id: string; name: string; address: string; active?: boolean }, Update: { id?: string; agency_id?: string; name?: string; address?: string; active?: boolean }, Relationships: [] },
    },
    Views: { },
    Functions: { },
    Enums: { trip_status: ['DRAFT', 'SALES_OPEN', 'SALES_CLOSED', 'CANCELLED', 'COMPLETED'], reservation_status: ['DRAFT', 'WAITING_ENTRY', 'CONFIRMED', 'CANCELLED', 'EXPIRED', 'COMPLETED'] },
  }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>
type DefaultSchema = DatabaseWithoutInternals['public']
export type Tables<T extends keyof DefaultSchema['Tables']> = DefaultSchema['Tables'][T]
export type Row<T extends keyof DefaultSchema['Tables']> = DefaultSchema['Tables'][T]['Row']
export type Insert<T extends keyof DefaultSchema['Tables']> = DefaultSchema['Tables'][T]['Insert']
export type Update<T extends keyof DefaultSchema['Tables']> = DefaultSchema['Tables'][T]['Update']
export type Enum<T extends keyof DefaultSchema['Enums']> = DefaultSchema['Enums'][T]
