"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { serverSupabase } from "@/lib/supabase/server";
const databaseUuid=z.string().regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
export async function listReservationsAction(){const db=await serverSupabase();const {data}=await db.from("reservations").select("id,code,total_amount,status,financial_status,created_at").order("created_at",{ascending:false});return data??[];}
export async function reservationOptions(){const db=await serverSupabase();const [{data:allTrips},{data:customers}]=await Promise.all([db.from("trips").select("id,title,code,status").order("departure_at"),db.from("agency_customers").select("id,full_name").eq("status","ACTIVE").order("full_name")]);const trips=(allTrips??[]).filter(trip=>trip.status==="SALES_OPEN");return {trips,customers:customers??[]};}
export async function createReservationAction(form:FormData){const parsed=z.object({trip_id:databaseUuid,buyer_customer_id:databaseUuid,commercial_source:z.string().trim().min(1).max(40),sales_channel:z.string().trim().min(1).max(40),hold_minutes:z.coerce.number().int().min(1).max(1440)}).safeParse(Object.fromEntries(form));if(!parsed.success){const fields=parsed.error.issues.map(issue=>String(issue.path[0])).join(", ");redirect(`/technical/reservations/new?error=${encodeURIComponent(`Preencha corretamente: ${fields}.`)}`);}const db=await serverSupabase();const expires=new Date(Date.now()+parsed.data.hold_minutes*60000).toISOString();const {data,error}=await db.rpc("create_manual_reservation",{p_trip:parsed.data.trip_id,p_buyer:parsed.data.buyer_customer_id,p_source:parsed.data.commercial_source,p_channel:parsed.data.sales_channel,p_expires_at:expires});if(error||!data){const message=error?.code==="42501"?"Sua sessao nao possui permissao para criar esta reserva.":error?.code==="23503"?"A viagem ou o cliente nao esta mais disponivel.":"Nao foi possivel criar a reserva. Tente novamente.";redirect(`/technical/reservations/new?error=${encodeURIComponent(message)}`);}revalidatePath("/technical/reservations");redirect(`/technical/reservations/${data}`);}
export async function reservationDetail(id:string){const db=await serverSupabase();const [{data:reservation},{data:passengers}]=await Promise.all([db.from("reservations").select("id,code,trip_id,status,financial_status,total_amount,entry_amount,expires_at,trips(title,code)").eq("id",id).single(),db.from("reservation_passengers").select("id,passenger_name_snapshot,category_name_snapshot,boarding_snapshot,list_price,sale_price,status").eq("reservation_id",id).order("created_at")]);if(!reservation)return null;const [{data:availablePassengers},{data:boardingPoints},{data:charges},{data:payments}]=await Promise.all([db.from("agency_passengers").select("id,full_name,document,birth_date").eq("status","ACTIVE").order("full_name"),db.from("trip_boarding_points").select("id,name_snapshot,boarding_at").eq("trip_id",reservation.trip_id).order("sort_order"),db.from("charges").select("id,charge_type,amount,due_date,status,paid_at").eq("reservation_id",id).order("created_at"),db.from("payments").select("id,amount,provider,payment_method,status,confirmed_at,created_at").eq("reservation_id",id).order("created_at",{ascending:false})]);return {reservation,passengers:passengers??[],availablePassengers:availablePassengers??[],boardingPoints:boardingPoints??[],charges:charges??[],payments:payments??[]};}
export async function addReservationPassengerAction(reservationId:string,form:FormData){const parsed=z.object({passenger_id:databaseUuid,boarding_point_id:databaseUuid,sale_price:z.preprocess(v=>typeof v==="string"?v.replace(",","."):v,z.coerce.number().positive())}).safeParse(Object.fromEntries(form));if(!parsed.success)redirect(`/technical/reservations/${reservationId}?error=${encodeURIComponent("Selecione o passageiro, o embarque e informe um preco valido.")}`);const db=await serverSupabase();const {error}=await db.rpc("add_reservation_passenger",{p_reservation:reservationId,p_passenger:parsed.data.passenger_id,p_boarding:parsed.data.boarding_point_id,p_sale_price:parsed.data.sale_price});if(error){const message=error.message.includes("discount approval")?"O preco informado exige aprovacao comercial. Para a demonstracao, use 900,00.":error.code==="P0001"?"Nao ha mais capacidade disponivel nesta viagem.":error.code==="23503"?"Os dados do passageiro ou do embarque nao estao disponiveis.":"Nao foi possivel adicionar o passageiro.";redirect(`/technical/reservations/${reservationId}?error=${encodeURIComponent(message)}`);}revalidatePath(`/technical/reservations/${reservationId}`);}
export async function submitReservationAction(reservationId:string){const db=await serverSupabase();const {error}=await db.rpc("submit_reservation",{p_reservation:reservationId});if(error)return;revalidatePath(`/technical/reservations/${reservationId}`);revalidatePath("/technical/reservations");}
const moneyInput=z.string().trim().regex(/^\d+(?:[.,]\d{1,2})?$/).transform(value=>Number(value.replace(",",".")));
export async function configureEntryChargeAction(reservationId:string,form:FormData){const parsed=z.object({entry_amount:moneyInput,due_date:z.string().trim().optional()}).safeParse(Object.fromEntries(form));if(!parsed.success)return;const db=await serverSupabase();const {error}=await db.rpc("configure_reservation_charges",{p_reservation:reservationId,p_entry_amount:parsed.data.entry_amount,p_due_date:parsed.data.due_date||undefined});if(!error)revalidatePath(`/technical/reservations/${reservationId}`);}
export async function configureBalanceInstallmentsAction(reservationId:string,form:FormData){const parsed=z.object({installments:z.coerce.number().int().min(1).max(24),first_due_date:z.string().trim().optional()}).safeParse(Object.fromEntries(form));if(!parsed.success)redirect(`/technical/reservations/${reservationId}?error=${encodeURIComponent("Informe de 1 a 24 parcelas.")}`);const db=await serverSupabase();const {error}=await db.rpc("configure_reservation_balance",{p_reservation:reservationId,p_installments:parsed.data.installments,p_first_due_date:parsed.data.first_due_date||undefined});if(error){const message=error.code==="23505"?"O saldo desta reserva ja foi programado.":"Nao foi possivel programar o saldo.";redirect(`/technical/reservations/${reservationId}?error=${encodeURIComponent(message)}`);}revalidatePath(`/technical/reservations/${reservationId}`);}
export async function registerCashPaymentAction(reservationId:string,form:FormData){const parsed=z.object({charge_id:databaseUuid,amount:moneyInput}).safeParse(Object.fromEntries(form));if(!parsed.success)return;const db=await serverSupabase();const {error}=await db.rpc("register_cash_payment",{p_charge:parsed.data.charge_id,p_amount:parsed.data.amount,p_idempotency_key:crypto.randomUUID()});if(!error){revalidatePath(`/technical/reservations/${reservationId}`);revalidatePath("/technical/reservations");}}
