"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { serverSupabase } from "@/lib/supabase/server";
export async function listReservationsAction(){const db=await serverSupabase();const {data}=await db.from("reservations").select("id,code,total_amount,status,financial_status,created_at").order("created_at",{ascending:false});return data??[];}
export async function reservationOptions(){const db=await serverSupabase();const [{data:trips},{data:customers}]=await Promise.all([db.from("trips").select("id,title,code").eq("status","SALES_OPEN").order("departure_at"),db.from("agency_customers").select("id,full_name").eq("status","ACTIVE").order("full_name")]);return {trips:trips??[],customers:customers??[]};}
export async function createReservationAction(form:FormData){const parsed=z.object({trip_id:z.uuid(),buyer_customer_id:z.uuid(),commercial_source:z.string().trim().min(1).max(40),sales_channel:z.string().trim().min(1).max(40),hold_minutes:z.coerce.number().int().min(1).max(1440)}).safeParse(Object.fromEntries(form));if(!parsed.success)return;const db=await serverSupabase();const expires=new Date(Date.now()+parsed.data.hold_minutes*60000).toISOString();const {data,error}=await db.rpc("create_manual_reservation",{p_trip:parsed.data.trip_id,p_buyer:parsed.data.buyer_customer_id,p_source:parsed.data.commercial_source,p_channel:parsed.data.sales_channel,p_expires_at:expires});if(error||!data)return;revalidatePath("/technical/reservations");redirect(`/technical/reservations/${data}`);}
export async function reservationDetail(id:string){const db=await serverSupabase();const [{data:reservation},{data:passengers}]=await Promise.all([db.from("reservations").select("id,code,trip_id,status,total_amount,expires_at,trips(title,code)").eq("id",id).single(),db.from("reservation_passengers").select("id,passenger_name_snapshot,category_name_snapshot,boarding_snapshot,list_price,sale_price,status").eq("reservation_id",id).order("created_at")]);if(!reservation)return null;const [{data:availablePassengers},{data:boardingPoints}]=await Promise.all([db.from("agency_passengers").select("id,full_name,document,birth_date").eq("status","ACTIVE").order("full_name"),db.from("trip_boarding_points").select("id,name_snapshot,boarding_at").eq("trip_id",reservation.trip_id).order("sort_order")]);return {reservation,passengers:passengers??[],availablePassengers:availablePassengers??[],boardingPoints:boardingPoints??[]};}
export async function addReservationPassengerAction(reservationId:string,form:FormData){const parsed=z.object({passenger_id:z.uuid(),boarding_point_id:z.uuid(),sale_price:z.preprocess(v=>typeof v==="string"?v.replace(",","."):v,z.coerce.number().nonnegative())}).safeParse(Object.fromEntries(form));if(!parsed.success)return;const db=await serverSupabase();const {error}=await db.rpc("add_reservation_passenger",{p_reservation:reservationId,p_passenger:parsed.data.passenger_id,p_boarding:parsed.data.boarding_point_id,p_sale_price:parsed.data.sale_price});if(!error)revalidatePath(`/technical/reservations/${reservationId}`);}
export async function submitReservationAction(reservationId:string){const db=await serverSupabase();const {error}=await db.rpc("submit_reservation",{p_reservation:reservationId});if(error)return;revalidatePath(`/technical/reservations/${reservationId}`);revalidatePath("/technical/reservations");}
