begin;

create type public.trip_status as enum ('DRAFT','SALES_OPEN','SALES_CLOSED','CANCELLED','COMPLETED');
create type public.site_publication_status as enum ('DRAFT','PUBLISHED','UNPUBLISHED');
create type public.trip_cost_type as enum ('FIXED','PER_PASSENGER');
create type public.cost_allocation_type as enum ('DIRECT_PER_PASSENGER','SHARED','FIXED_NO_ALLOCATION');

insert into public.permissions(key,description) values
 ('trips.view','Visualizar viagens'),('trips.create','Criar e duplicar viagens'),
 ('trips.edit','Editar viagens'),('trips.publish','Publicar viagens'),
 ('trips.costs.view','Visualizar custos'),('trips.costs.edit','Editar custos')
on conflict(key) do update set description=excluded.description;

alter table public.passenger_categories add column min_age integer check(min_age is null or min_age>=0), add column max_age integer check(max_age is null or max_age>=0), add column occupies_seat_default boolean not null default true, add column sort_order integer not null default 0, add constraint passenger_categories_age_range check(min_age is null or max_age is null or min_age<=max_age);

create table public.trips(
 id uuid primary key default gen_random_uuid(), agency_id uuid not null references public.agencies(id) on delete cascade,
 code text not null, title text not null check(length(trim(title)) between 3 and 160), slug text not null check(slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'), destination text not null, category text,
 departure_at timestamptz not null, return_at timestamptz not null, sales_start_at timestamptz, sales_end_at timestamptz,
 minimum_passengers integer check(minimum_passengers is null or minimum_passengers>0), minimum_passenger_decision_date date,
 status public.trip_status not null default 'DRAFT', featured boolean not null default false, private boolean not null default false,
 contract_pending boolean not null default true, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz,
 unique(agency_id,id), unique(agency_id,code), unique(agency_id,slug), check(return_at>departure_at), check(sales_end_at is null or sales_start_at is null or sales_end_at>sales_start_at), check(sales_end_at is null or sales_end_at<=departure_at)
);
create table public.trip_content(agency_id uuid not null,trip_id uuid primary key,description text not null default '',included_items text[] not null default '{}',excluded_items text[] not null default '{}',insurance_included boolean not null default false,updated_at timestamptz not null default now(),foreign key(agency_id,trip_id) references public.trips(agency_id,id) on delete cascade);
create table public.trip_images(id uuid primary key default gen_random_uuid(),agency_id uuid not null,trip_id uuid not null,storage_path text not null check(storage_path ~ '^trip-images/[0-9a-f-]+/[A-Za-z0-9._/-]+$'),mime_type text not null check(mime_type in ('image/jpeg','image/png','image/webp')),size_bytes bigint not null check(size_bytes between 1 and 10485760),alt_text text not null,sort_order integer not null default 0,created_at timestamptz not null default now(),unique(agency_id,id),foreign key(agency_id,trip_id) references public.trips(agency_id,id) on delete cascade);
create table public.trip_itinerary_items(id uuid primary key default gen_random_uuid(),agency_id uuid not null,trip_id uuid not null,day_number integer not null check(day_number>0),title text not null,description text not null default '',sort_order integer not null default 0,unique(agency_id,id),foreign key(agency_id,trip_id) references public.trips(agency_id,id) on delete cascade);
create table public.trip_boarding_points(id uuid primary key default gen_random_uuid(),agency_id uuid not null,trip_id uuid not null,source_location_id uuid,address_snapshot text not null,name_snapshot text not null,boarding_at timestamptz not null,advance_minutes integer check(advance_minutes between 0 and 1440),tolerance_minutes integer check(tolerance_minutes between 0 and 1440),sort_order integer not null default 0,unique(agency_id,id),foreign key(agency_id,trip_id) references public.trips(agency_id,id) on delete cascade,foreign key(source_location_id,agency_id) references public.agency_boarding_locations(id,agency_id));
create table public.trip_passenger_prices(id uuid primary key default gen_random_uuid(),agency_id uuid not null,trip_id uuid not null,passenger_category_id uuid not null,list_price numeric(14,2) not null check(list_price>=0),minimum_price_without_approval numeric(14,2) check(minimum_price_without_approval between 0 and list_price),occupies_seat boolean not null,active boolean not null default true,unique(agency_id,id),unique(trip_id,passenger_category_id),foreign key(agency_id,trip_id) references public.trips(agency_id,id) on delete cascade,foreign key(passenger_category_id,agency_id) references public.passenger_categories(id,agency_id));
create table public.transport_suppliers(id uuid primary key default gen_random_uuid(),agency_id uuid not null references public.agencies(id) on delete cascade,name text not null,contact_name text,contact_phone text,active boolean not null default true,created_at timestamptz not null default now(),unique(agency_id,id),unique(agency_id,name));
create table public.vehicle_templates(id uuid primary key default gen_random_uuid(),agency_id uuid not null references public.agencies(id) on delete cascade,name text not null,capacity integer not null check(capacity>0),has_seat_map boolean not null default true,active boolean not null default true,created_at timestamptz not null default now(),unique(agency_id,id),unique(agency_id,name));
create table public.vehicle_template_seats(id uuid primary key default gen_random_uuid(),agency_id uuid not null,vehicle_template_id uuid not null,label text not null,row_number integer,column_number integer,active boolean not null default true,blocked boolean not null default false,unique(agency_id,id),unique(vehicle_template_id,label),foreign key(agency_id,vehicle_template_id) references public.vehicle_templates(agency_id,id) on delete cascade);
create table public.trip_vehicle_assignments(id uuid primary key default gen_random_uuid(),agency_id uuid not null,trip_id uuid not null,vehicle_template_id uuid,supplier_id uuid,capacity_snapshot integer not null check(capacity_snapshot>0),estimated_cost numeric(14,2) check(estimated_cost>=0),confirmed_cost numeric(14,2) check(confirmed_cost>=0),actual_cost numeric(14,2) check(actual_cost>=0),started_at timestamptz not null default now(),ended_at timestamptz,reason text not null,created_by uuid not null references auth.users(id),unique(agency_id,id),foreign key(agency_id,trip_id) references public.trips(agency_id,id),foreign key(agency_id,vehicle_template_id) references public.vehicle_templates(agency_id,id),foreign key(agency_id,supplier_id) references public.transport_suppliers(agency_id,id),check(ended_at is null or ended_at>=started_at));
create unique index trip_one_current_vehicle on public.trip_vehicle_assignments(trip_id) where ended_at is null;
create table public.trip_seats(id uuid primary key default gen_random_uuid(),agency_id uuid not null,trip_id uuid not null,assignment_id uuid not null,label text not null,active boolean not null default true,blocked boolean not null default false,requires_review boolean not null default false,unique(agency_id,id),unique(assignment_id,label),foreign key(agency_id,trip_id) references public.trips(agency_id,id),foreign key(agency_id,assignment_id) references public.trip_vehicle_assignments(agency_id,id) on delete cascade);
create table public.trip_costs(id uuid primary key default gen_random_uuid(),agency_id uuid not null,trip_id uuid not null,category text not null,description text not null,cost_type public.trip_cost_type not null,allocation_type public.cost_allocation_type not null,estimated_amount numeric(14,2) not null check(estimated_amount>=0),confirmed_amount numeric(14,2) check(confirmed_amount>=0),actual_amount numeric(14,2) check(actual_amount>=0),supplier_name text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(agency_id,id),foreign key(agency_id,trip_id) references public.trips(agency_id,id) on delete cascade);
create table public.site_trip_publications(agency_id uuid not null,trip_id uuid primary key,status public.site_publication_status not null default 'DRAFT',published_at timestamptz,updated_at timestamptz not null default now(),foreign key(agency_id,trip_id) references public.trips(agency_id,id) on delete cascade);

create or replace function public.age_on_date(birth_date date,reference_date date) returns integer language sql immutable strict as $$ select extract(year from age(reference_date,birth_date))::integer $$;
create or replace function public.trip_price_for_birth_date(p_trip uuid,p_birth_date date) returns table(category_id uuid,list_price numeric,occupies_seat boolean) language sql stable security definer set search_path=public as $$ select p.passenger_category_id,p.list_price,p.occupies_seat from trips t join trip_passenger_prices p on p.trip_id=t.id and p.active join passenger_categories c on c.id=p.passenger_category_id and c.agency_id=t.agency_id where t.id=p_trip and has_agency_permission(t.agency_id,'trips.view') and (c.min_age is null or age_on_date(p_birth_date,t.departure_at::date)>=c.min_age) and (c.max_age is null or age_on_date(p_birth_date,t.departure_at::date)<=c.max_age) order by c.sort_order,c.name limit 1 $$;
create or replace function public.assign_trip_vehicle(p_trip uuid,p_template uuid,p_supplier uuid,p_reason text) returns uuid language plpgsql security definer set search_path=public as $$ declare a uuid; n uuid; previous_id uuid; cap integer; incompatible boolean; begin select agency_id into a from trips where id=p_trip and has_agency_permission(agency_id,'trips.edit') for update; if a is null then raise exception 'trip unavailable' using errcode='42501'; end if; select capacity into cap from vehicle_templates where id=p_template and agency_id=a; if cap is null then raise exception 'vehicle unavailable' using errcode='23503'; end if; select id into previous_id from trip_vehicle_assignments where trip_id=p_trip and ended_at is null for update; update trip_vehicle_assignments set ended_at=now() where id=previous_id; insert into trip_vehicle_assignments(agency_id,trip_id,vehicle_template_id,supplier_id,capacity_snapshot,reason,created_by) values(a,p_trip,p_template,p_supplier,cap,p_reason,auth.uid()) returning id into n; insert into trip_seats(agency_id,trip_id,assignment_id,label,active,blocked) select a,p_trip,n,label,active,blocked from vehicle_template_seats where vehicle_template_id=p_template; if (select count(*) from trip_seats where assignment_id=n and active and not blocked)>cap then raise exception 'seat map exceeds vehicle capacity' using errcode='23514'; end if; if previous_id is not null then select exists((select label from trip_seats where assignment_id=previous_id and active except select label from trip_seats where assignment_id=n and active) union all (select label from trip_seats where assignment_id=n and active except select label from trip_seats where assignment_id=previous_id and active)) into incompatible; if incompatible then update trip_seats set requires_review=true where assignment_id=n; end if; end if; return n; end $$;
create or replace function public.duplicate_trip(p_trip uuid,p_code text,p_slug text) returns uuid language plpgsql security definer set search_path=public as $$ declare o trips%rowtype; n uuid; begin select * into o from trips where id=p_trip and has_agency_permission(agency_id,'trips.create'); if o.id is null then raise exception 'trip unavailable' using errcode='42501'; end if; insert into trips(agency_id,code,title,slug,destination,category,departure_at,return_at,sales_start_at,sales_end_at,minimum_passengers,minimum_passenger_decision_date,created_by) values(o.agency_id,p_code,o.title,p_slug,o.destination,o.category,o.departure_at,o.return_at,o.sales_start_at,o.sales_end_at,o.minimum_passengers,o.minimum_passenger_decision_date,auth.uid()) returning id into n; insert into trip_content select agency_id,n,description,included_items,excluded_items,insurance_included,now() from trip_content where trip_id=p_trip; insert into trip_itinerary_items(agency_id,trip_id,day_number,title,description,sort_order) select agency_id,n,day_number,title,description,sort_order from trip_itinerary_items where trip_id=p_trip; insert into trip_boarding_points(agency_id,trip_id,source_location_id,address_snapshot,name_snapshot,boarding_at,advance_minutes,tolerance_minutes,sort_order) select agency_id,n,source_location_id,address_snapshot,name_snapshot,boarding_at,advance_minutes,tolerance_minutes,sort_order from trip_boarding_points where trip_id=p_trip; insert into trip_passenger_prices(agency_id,trip_id,passenger_category_id,list_price,minimum_price_without_approval,occupies_seat,active) select agency_id,n,passenger_category_id,list_price,minimum_price_without_approval,occupies_seat,active from trip_passenger_prices where trip_id=p_trip; insert into site_trip_publications values(o.agency_id,n,'DRAFT',null,now()); return n; end $$;
create or replace view public.public_trip_catalog as select t.id,t.agency_id,t.title,t.slug,t.destination,t.departure_at,t.return_at,t.featured,c.description,c.included_items,c.excluded_items from trips t join site_trip_publications p on p.trip_id=t.id and p.status='PUBLISHED' join trip_content c on c.trip_id=t.id where t.archived_at is null and not t.private and t.status in ('SALES_OPEN','SALES_CLOSED');

do $$ declare t text; begin foreach t in array array['trips','trip_content','trip_images','trip_itinerary_items','trip_boarding_points','trip_passenger_prices','transport_suppliers','vehicle_templates','vehicle_template_seats','trip_vehicle_assignments','trip_seats','trip_costs','site_trip_publications'] loop execute format('alter table public.%I enable row level security',t); execute format('alter table public.%I force row level security',t); execute format('create policy %I on public.%I for select using(public.has_agency_permission(agency_id,''trips.view''))',t||'_read',t); execute format('create policy %I on public.%I for all using(public.has_agency_permission(agency_id,''trips.edit'')) with check(public.has_agency_permission(agency_id,''trips.edit''))',t||'_write',t); execute format('grant select,insert,update,delete on public.%I to authenticated',t); end loop; end $$;
do $$ declare t text; begin foreach t in array array['trips','trip_content','trip_images','trip_itinerary_items','trip_boarding_points','trip_passenger_prices','transport_suppliers','vehicle_templates','vehicle_template_seats','trip_vehicle_assignments','trip_seats','trip_costs','site_trip_publications'] loop execute format('create trigger %I before update on public.%I for each row execute function public.prevent_tenant_transfer()',t||'_immutable_tenant',t); end loop; end $$;
drop policy site_trip_publications_write on public.site_trip_publications; create policy site_trip_publications_write on public.site_trip_publications for all using(public.has_agency_permission(agency_id,'trips.publish')) with check(public.has_agency_permission(agency_id,'trips.publish'));
drop policy trip_costs_read on public.trip_costs; create policy trip_costs_read on public.trip_costs for select using(public.has_agency_permission(agency_id,'trips.costs.view'));
drop policy trip_costs_write on public.trip_costs; create policy trip_costs_write on public.trip_costs for all using(public.has_agency_permission(agency_id,'trips.costs.edit')) with check(public.has_agency_permission(agency_id,'trips.costs.edit'));
grant execute on function public.age_on_date(date,date),public.trip_price_for_birth_date(uuid,date),public.assign_trip_vehicle(uuid,uuid,uuid,text),public.duplicate_trip(uuid,text,text) to authenticated;
grant select on public.public_trip_catalog to anon,authenticated;
commit;
