begin;
create type public.reservation_status as enum ('DRAFT','WAITING_ENTRY','CONFIRMED','CANCELLED','EXPIRED','COMPLETED');
create type public.reservation_financial_status as enum ('PENDING','PARTIALLY_PAID','ENTRY_PAID','PAID','REFUNDED');
insert into public.permissions(key,description) values ('reservations.view','Visualizar reservas'),('reservations.create','Criar reservas'),('reservations.edit','Editar reservas'),('customers.view','Visualizar clientes'),('customers.create','Criar clientes'),('customers.edit','Editar clientes') on conflict(key) do update set description=excluded.description;

alter table public.agency_customers add column full_name text;
alter table public.agency_customers alter column display_name drop not null;
alter table public.agency_customers alter column auth_user_id drop not null;
alter table public.agency_customers add column email text,add column phone text,add column document text,add column birth_date date,add column status text not null default 'ACTIVE' check(status in('ACTIVE','ARCHIVED')),add column updated_at timestamptz not null default now(),add column archived_at timestamptz;
alter table public.agency_customers add constraint agency_customers_identity check(auth_user_id is not null or document is not null);
alter table public.agency_customers add constraint agency_customers_name check(coalesce(nullif(trim(full_name),''),nullif(trim(display_name),'')) is not null);
alter table public.agency_customers add constraint agency_customers_agency_id_id_key unique(agency_id,id);
create unique index agency_customers_document_unique on public.agency_customers(agency_id,document) where document is not null and archived_at is null;
create or replace function public.sync_customer_name() returns trigger language plpgsql set search_path=public as $$begin new.full_name=coalesce(nullif(trim(new.full_name),''),new.display_name);new.display_name=coalesce(nullif(trim(new.display_name),''),new.full_name);return new;end$$;
create trigger agency_customers_sync_name before insert or update of full_name,display_name on public.agency_customers for each row execute function public.sync_customer_name();

create table public.agency_passengers(id uuid primary key default gen_random_uuid(),agency_id uuid not null references public.agencies(id) on delete cascade,owner_customer_id uuid,linked_auth_user_id uuid references auth.users(id) on delete set null,full_name text not null check(length(trim(full_name)) between 2 and 160),document text not null,birth_date date not null,phone text,status text not null default 'ACTIVE' check(status in('ACTIVE','ARCHIVED')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(agency_id,id),unique(agency_id,document),foreign key(agency_id,owner_customer_id) references public.agency_customers(agency_id,id));
create table public.reservations(id uuid primary key default gen_random_uuid(),agency_id uuid not null references public.agencies(id) on delete cascade,trip_id uuid not null,buyer_customer_id uuid not null,code text not null,status public.reservation_status not null default 'DRAFT',financial_status public.reservation_financial_status not null default 'PENDING',commercial_source text not null,sales_channel text not null,currency text not null default 'BRL' check(currency~'^[A-Z]{3}$'),subtotal numeric(14,2) not null default 0 check(subtotal>=0),discount_total numeric(14,2) not null default 0 check(discount_total>=0),total_amount numeric(14,2) not null default 0 check(total_amount>=0),entry_amount numeric(14,2) not null default 0 check(entry_amount>=0),expires_at timestamptz not null,confirmed_at timestamptz,cancelled_at timestamptz,expired_at timestamptz,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(agency_id,id),unique(agency_id,code),foreign key(agency_id,trip_id) references public.trips(agency_id,id),foreign key(agency_id,buyer_customer_id) references public.agency_customers(agency_id,id),check(discount_total<=subtotal),check(total_amount=subtotal-discount_total));
create table public.approval_requests(id uuid primary key default gen_random_uuid(),agency_id uuid not null references public.agencies(id) on delete cascade,reservation_id uuid not null,passenger_id uuid,requested_sale_price numeric(14,2) not null check(requested_sale_price>=0),list_price numeric(14,2) not null check(list_price>=requested_sale_price),context_hash text not null,status text not null default 'PENDING' check(status in('PENDING','APPROVED','REJECTED','EXPIRED','CONSUMED')),reason text not null,requested_by uuid not null references auth.users(id),decided_by uuid references auth.users(id),decided_at timestamptz,created_at timestamptz not null default now(),expires_at timestamptz not null,unique(agency_id,id),foreign key(agency_id,reservation_id) references public.reservations(agency_id,id));
create table public.reservation_passengers(id uuid primary key default gen_random_uuid(),agency_id uuid not null references public.agencies(id) on delete cascade,reservation_id uuid not null,trip_id uuid not null,passenger_id uuid,passenger_name_snapshot text not null,document_snapshot text not null,birth_date_snapshot date not null,category_id uuid not null,category_name_snapshot text not null,boarding_point_id uuid not null,boarding_snapshot text not null,occupies_seat boolean not null,list_price numeric(14,2) not null check(list_price>=0),sale_price numeric(14,2) not null check(sale_price>=0),discount_amount numeric(14,2) generated always as(list_price-sale_price) stored,status text not null default 'ACTIVE' check(status in('ACTIVE','CANCELLED')),created_at timestamptz not null default now(),cancelled_at timestamptz,unique(agency_id,id),foreign key(agency_id,reservation_id) references public.reservations(agency_id,id) on delete cascade,foreign key(agency_id,trip_id) references public.trips(agency_id,id),foreign key(agency_id,passenger_id) references public.agency_passengers(agency_id,id),foreign key(agency_id,category_id) references public.passenger_categories(agency_id,id),foreign key(agency_id,boarding_point_id) references public.trip_boarding_points(agency_id,id),check(sale_price<=list_price));
create table public.seat_holds(id uuid primary key default gen_random_uuid(),agency_id uuid not null references public.agencies(id) on delete cascade,trip_id uuid not null,reservation_id uuid not null,seat_id uuid,expires_at timestamptz not null,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),unique(agency_id,id),foreign key(agency_id,trip_id) references public.trips(agency_id,id),foreign key(agency_id,reservation_id) references public.reservations(agency_id,id) on delete cascade,foreign key(agency_id,seat_id) references public.trip_seats(agency_id,id));
create unique index seat_holds_active_seat on public.seat_holds(trip_id,seat_id) where seat_id is not null;
create table public.seat_assignments(id uuid primary key default gen_random_uuid(),agency_id uuid not null references public.agencies(id) on delete cascade,trip_id uuid not null,reservation_passenger_id uuid not null,seat_id uuid not null,assigned_at timestamptz not null default now(),released_at timestamptz,release_reason text,unique(agency_id,id),foreign key(agency_id,reservation_passenger_id) references public.reservation_passengers(agency_id,id),foreign key(agency_id,seat_id) references public.trip_seats(agency_id,id));
create unique index seat_assignments_active_seat on public.seat_assignments(trip_id,seat_id) where released_at is null;
create table public.sales_attributions(id uuid primary key default gen_random_uuid(),agency_id uuid not null references public.agencies(id) on delete cascade,reservation_id uuid not null,source text not null,channel text not null,created_at timestamptz not null default now(),unique(agency_id,reservation_id),foreign key(agency_id,reservation_id) references public.reservations(agency_id,id) on delete cascade);

create or replace function public.create_manual_reservation(p_trip uuid,p_buyer uuid,p_source text,p_channel text,p_expires_at timestamptz) returns uuid language plpgsql security definer set search_path=public as $$ declare a uuid;r uuid;begin select agency_id into a from trips where id=p_trip and status='SALES_OPEN' and archived_at is null and has_agency_permission(agency_id,'reservations.create');if a is null then raise exception 'trip unavailable' using errcode='42501';end if;if p_expires_at<=now() then raise exception 'invalid expiration' using errcode='22023';end if;if not exists(select 1 from agency_customers where id=p_buyer and agency_id=a and status='ACTIVE') then raise exception 'buyer unavailable' using errcode='23503';end if;insert into reservations(agency_id,trip_id,buyer_customer_id,code,commercial_source,sales_channel,expires_at,created_by) values(a,p_trip,p_buyer,'RES-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,10)),trim(p_source),trim(p_channel),p_expires_at,auth.uid()) returning id into r;insert into sales_attributions(agency_id,reservation_id,source,channel) values(a,r,trim(p_source),trim(p_channel));return r;end$$;
create or replace function public.add_reservation_passenger(p_reservation uuid,p_passenger uuid,p_boarding uuid,p_sale_price numeric,p_seat uuid default null) returns uuid language plpgsql security definer set search_path=public as $$
declare r reservations%rowtype;p agency_passengers%rowtype;pr record;bp trip_boarding_points%rowtype;cap integer;used integer;rp uuid;begin
 select * into r from reservations where id=p_reservation and status='DRAFT' and expires_at>now() and has_agency_permission(agency_id,'reservations.edit') for update;
 if r.id is null then raise exception 'reservation unavailable' using errcode='42501';end if;
 perform pg_advisory_xact_lock(hashtextextended(r.trip_id::text,0));
 select * into p from agency_passengers where id=p_passenger and agency_id=r.agency_id and status='ACTIVE';
 select pc.id,pc.name,tp.list_price,tp.minimum_price_without_approval,tp.occupies_seat into pr from trip_passenger_prices tp join passenger_categories pc on pc.id=tp.passenger_category_id and pc.agency_id=tp.agency_id where tp.trip_id=r.trip_id and tp.active and (pc.min_age is null or age_on_date(p.birth_date,(select departure_at::date from trips where id=r.trip_id))>=pc.min_age) and (pc.max_age is null or age_on_date(p.birth_date,(select departure_at::date from trips where id=r.trip_id))<=pc.max_age) order by pc.sort_order limit 1;
 select * into bp from trip_boarding_points where id=p_boarding and trip_id=r.trip_id and agency_id=r.agency_id;
 if p.id is null or pr.id is null or bp.id is null then raise exception 'passenger data unavailable' using errcode='23503';end if;
 if p_sale_price<coalesce(pr.minimum_price_without_approval,pr.list_price) and not exists(select 1 from approval_requests where reservation_id=r.id and passenger_id=p.id and requested_sale_price=p_sale_price and context_hash=encode(digest(r.trip_id::text||':'||p.id::text||':'||p_sale_price::text,'sha256'),'hex') and status='APPROVED' and expires_at>now()) then raise exception 'discount approval required' using errcode='42501';end if;
 if pr.occupies_seat then select capacity_snapshot into cap from trip_vehicle_assignments where trip_id=r.trip_id and ended_at is null;select (select count(*) from reservation_passengers x join reservations z on z.id=x.reservation_id where x.trip_id=r.trip_id and x.occupies_seat and x.status='ACTIVE' and z.status='CONFIRMED')+(select count(*) from seat_holds where trip_id=r.trip_id and expires_at>now()) into used;if coalesce(cap,0)<=used then raise exception 'capacity unavailable' using errcode='P0001';end if;if p_seat is not null and (exists(select 1 from seat_assignments where trip_id=r.trip_id and seat_id=p_seat and released_at is null) or exists(select 1 from seat_holds where trip_id=r.trip_id and seat_id=p_seat and expires_at>now())) then raise exception 'seat unavailable' using errcode='23505';end if;end if;
 insert into reservation_passengers(agency_id,reservation_id,trip_id,passenger_id,passenger_name_snapshot,document_snapshot,birth_date_snapshot,category_id,category_name_snapshot,boarding_point_id,boarding_snapshot,occupies_seat,list_price,sale_price) values(r.agency_id,r.id,r.trip_id,p.id,p.full_name,p.document,p.birth_date,pr.id,pr.name,bp.id,bp.name_snapshot,pr.occupies_seat,pr.list_price,p_sale_price) returning id into rp;
 if pr.occupies_seat then insert into seat_holds(agency_id,trip_id,reservation_id,seat_id,expires_at,created_by) values(r.agency_id,r.trip_id,r.id,p_seat,r.expires_at,auth.uid());end if;
 update reservations set subtotal=(select coalesce(sum(list_price),0) from reservation_passengers where reservation_id=r.id and status='ACTIVE'),discount_total=(select coalesce(sum(discount_amount),0) from reservation_passengers where reservation_id=r.id and status='ACTIVE'),total_amount=(select coalesce(sum(sale_price),0) from reservation_passengers where reservation_id=r.id and status='ACTIVE'),updated_at=now() where id=r.id;return rp;end$$;
create or replace function public.expire_reservations() returns integer language plpgsql security definer set search_path=public as $$declare n integer;begin update reservations set status='EXPIRED',expired_at=now(),updated_at=now() where status in('DRAFT','WAITING_ENTRY') and expires_at<=now();get diagnostics n=row_count;delete from seat_holds where expires_at<=now() or reservation_id in(select id from reservations where status in('EXPIRED','CANCELLED'));return n;end$$;
create or replace function public.submit_reservation(p_reservation uuid) returns void language plpgsql security definer set search_path=public as $$begin update reservations r set status='WAITING_ENTRY',updated_at=now() where id=p_reservation and status='DRAFT' and expires_at>now() and exists(select 1 from reservation_passengers where reservation_id=r.id and status='ACTIVE') and has_agency_permission(r.agency_id,'reservations.edit');if not found then raise exception 'reservation unavailable' using errcode='42501';end if;end$$;

do $$declare t text;begin foreach t in array array['agency_passengers','reservations','reservation_passengers','seat_holds','seat_assignments','approval_requests','sales_attributions'] loop execute format('alter table public.%I enable row level security',t);execute format('alter table public.%I force row level security',t);execute format('create trigger %I before update on public.%I for each row execute function public.prevent_tenant_transfer()',t||'_immutable_tenant',t);end loop;end$$;
drop policy customers_insert_owner on public.agency_customers;drop policy customers_update_owner on public.agency_customers;drop policy customers_read_member_or_owner on public.agency_customers;
create policy customers_read on public.agency_customers for select using(has_agency_permission(agency_id,'customers.view') or auth_user_id=auth.uid());create policy customers_write on public.agency_customers for all using(has_agency_permission(agency_id,'customers.edit')) with check(has_agency_permission(agency_id,'customers.create'));
do $$declare t text;begin foreach t in array array['agency_passengers'] loop execute format('create policy %I on public.%I for select using(has_agency_permission(agency_id,''customers.view''))',t||'_read',t);execute format('create policy %I on public.%I for all using(has_agency_permission(agency_id,''customers.edit'')) with check(has_agency_permission(agency_id,''customers.create''))',t||'_write',t);end loop;foreach t in array array['reservations','reservation_passengers','seat_holds','seat_assignments','approval_requests','sales_attributions'] loop execute format('create policy %I on public.%I for select using(has_agency_permission(agency_id,''reservations.view''))',t||'_read',t);execute format('create policy %I on public.%I for all using(has_agency_permission(agency_id,''reservations.edit'')) with check(has_agency_permission(agency_id,''reservations.create''))',t||'_write',t);end loop;end$$;
grant select,insert,update,delete on public.agency_customers,public.agency_passengers,public.reservations,public.reservation_passengers,public.seat_holds,public.seat_assignments,public.approval_requests,public.sales_attributions to authenticated;
grant execute on function public.create_manual_reservation(uuid,uuid,text,text,timestamptz),public.add_reservation_passenger(uuid,uuid,uuid,numeric,uuid),public.submit_reservation(uuid),public.expire_reservations() to authenticated;
commit;


